name: Main

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5

      - uses: oven-sh/setup-bun@v2

      - name: Build
        run: dotnet fsi ./build.fsx
        env:
          VITE_API_ROOT: ${{ secrets.API_ROOT }}

      - name: Obtain NuGet key
        uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544
        id: nuget-login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push to NuGet
        run: dotnet fsi build.fsx --push
        env:
          NUGET_KEY: ${{ steps.nuget-login.outputs.NUGET_API_KEY }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        
      - name: Setup dotnet v10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore local tools
        run: dotnet tool restore

      - name: Package lambda
        working-directory: tool/server
        run: dotnet lambda package

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: telplin
          work-dir: ./src/Telplin.Deploy
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}